### PR TITLE
 Support for .net standard

### PR DESCRIPTION
**Pull request by twenzel**
- Upgrade to new project format
- upgrade to netstandard1.4
- Upgrade to Remotion.Linq 2.2

### CODE REVIEW

**Comment by MichaelKetting** [comment]
Hi Tony,

I'm sorry but I can't integrate this PR, there's a couple of issues:
* I do not want to typically mix dependency upgrades and features, in this case, the project format, supporting .net standard and the upgrade of Remotion.Linq are three separate things.
* We have to provide a full framework build (net45) next to the netstandard build and given the recommendations by microsoft, also a .net standard 2.0 build.
* The build infrastructure itself is not yet able to handle .net standard builds. I'm actually working on one of the build blocks right now, but there's several more to go.
** supporting .net standard for dependency tracking tool
** supporting .net standard for our internal packaging tool
** supporting portable PDBs during the build
** supporting the latest version of nuget
** supporting unit tests for .net Core
** supporting parallel unit test runs during the build process to keep the build time reasonable
** changing AssemblyInfoShared to use properties and a build-generated AssemblyInfo-file.
** probably some other dependencies I haven't thought of right now.
* We will also have to decide on the version number, e.g. is this a minor or a major version.

**Comment by awaescher** [comment]
Hi Michael,

any news about this?

**Comment by MichaelKetting** [comment]
> Hi Michael,
> 
> any news about this?

Hi @awaescher, actually yeah. Pending unforseen scheduling conflicts, we should have .NET Standard sometime later this year.

**Comment by awaescher** [comment]
Sounds good. Anything the community could help out with?

**Comment by MichaelKetting** [comment]
Thanks for asking. It's mostly a question of updating our build infrastructure to support CPS projects, which doesn't lend itself to a community effort. Once that's done, the rest should be fairly straight forward and we'll be using Linq and Linq.SqlBackend as a test bed for the new infrastructure anyway.

**Comment by MichaelKetting** [comment]
@Stefan-Ilic, @iam-mholle you might want to keep an eye on this thread when we get to updating the build infrastructure.

**Pull request closed without merging**
